### ISSUE TITLE
DDS crash

### ISSUE THREAD

**Issue by hdunderscore** [JSandusky/UrContent#1]
From my initial testing, previewing dds textures in list view crashes the application.

**Comment by JSandusky** [comment]
Odd. I haven't had any problems with dds textures. Is it any DDS texture or perhaps a certain kind of DDS texture?

I'll wrap things up in some error handling though so at least won't crash if it can't load a file preview.

**Comment by hdunderscore** [comment]
It happened with the dds textures that come with urho, I didn't look further than that.

**Comment by JSandusky** [comment]
What OS are you using? 

It might be necessary for me to add DevILSharp or such as a dependency for reading DDS on platforms that don't handle it themselves (Win8 does out of the box, I'm not sure if Win7 does out of the box, and thinking about it I know Win Vista doesn't out of the box).

**Comment by hdunderscore** [comment]
I am using Windows  7. Upon debugging the message received was that it couldn't, like you said.

I pulled the latest changes, great work ! DDS's are loading and no crashes, big thanks for the response !

**Comment by JSandusky** [comment]
No problem. Glad FreeImage does the trick, seems to be a bit faster than using the WIC codecs as well.
